// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "33cd88c4-f256-4a31-8c37-891fea4e428a";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onCloudPaletteSetIndexChange();
void onCloudSelectedPaletteChange();
void onEffectColorChange();
void onButtonCountdownChange();
void onButtonDripChange();
void onButtonGlitterChange();
void onButtonJuggleChange();
void onButtonMatrixChange();
void onButtonPacificaChange();
void onButtonRainbowChange();

int cloudPaletteSetIndex;
int cloudSelectedPalette;
int effectColor;
bool buttonCountdown;
bool buttonDrip;
bool buttonGlitter;
bool buttonJuggle;
bool buttonMatrix;
bool buttonPacifica;
bool buttonRainbow;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(cloudPaletteSetIndex, READWRITE, ON_CHANGE, onCloudPaletteSetIndexChange);
  ArduinoCloud.addProperty(cloudSelectedPalette, READWRITE, ON_CHANGE, onCloudSelectedPaletteChange);
  ArduinoCloud.addProperty(effectColor, READWRITE, ON_CHANGE, onEffectColorChange);
  ArduinoCloud.addProperty(buttonCountdown, READWRITE, ON_CHANGE, onButtonCountdownChange);
  ArduinoCloud.addProperty(buttonDrip, READWRITE, ON_CHANGE, onButtonDripChange);
  ArduinoCloud.addProperty(buttonGlitter, READWRITE, ON_CHANGE, onButtonGlitterChange);
  ArduinoCloud.addProperty(buttonJuggle, READWRITE, ON_CHANGE, onButtonJuggleChange);
  ArduinoCloud.addProperty(buttonMatrix, READWRITE, ON_CHANGE, onButtonMatrixChange);
  ArduinoCloud.addProperty(buttonPacifica, READWRITE, ON_CHANGE, onButtonPacificaChange);
  ArduinoCloud.addProperty(buttonRainbow, READWRITE, ON_CHANGE, onButtonRainbowChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
