// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "33cd88c4-f256-4a31-8c37-891fea4e428a";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onCloudPaletteSetIndexChange();
void onCloudSelectedPaletteChange();
void onEffectColorChange();
void onActiveEffectChange();
void onResetDeviceChange();

int cloudPaletteSetIndex;
int cloudSelectedPalette;
int effectColor;
int activeEffect;
bool resetDevice;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(cloudPaletteSetIndex, READWRITE, ON_CHANGE, onCloudPaletteSetIndexChange);
  ArduinoCloud.addProperty(cloudSelectedPalette, READWRITE, ON_CHANGE, onCloudSelectedPaletteChange);
  ArduinoCloud.addProperty(effectColor, READWRITE, ON_CHANGE, onEffectColorChange);
  ArduinoCloud.addProperty(activeEffect, READWRITE, ON_CHANGE, onActiveEffectChange);
  ArduinoCloud.addProperty(resetDevice, READWRITE, ON_CHANGE, onResetDeviceChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
